### ISSUE TITLE
Additional links

### ISSUE THREAD

**Issue by ljosberinn** [kieranmv95/Front-End-Wizard#1]
Hi,

just thought I'd fill up your list with additional links I found useful and think they'd fit in.

## HTML
:globe_with_meridians: [HTML5 Pattern Cheat-Sheet](http://html5pattern.com/)
🌐 [SRI Hash Generator](https://www.srihash.org/)

## CSS
📚 [Prefetching, Preloading, Prebrowsing](https://css-tricks.com/prefetching-preloading-prebrowsing/)
🌐 [Normalize.css - A modern alternative to CSS resets](https://github.com/necolas/normalize.css)
🌐 [Simple CSS Cards](http://druchan.com/cards.sass/)
🌐 [Decorative motion hover effects for grid items](https://tympanus.net/Development/StackMotionHoverEffects/)
🌐 [A cross-browser library of CSS animations](https://daneden.github.io/animate.css/)
🌐 [Complete set of Instagram filters in pure CSS](https://picturepan2.github.io/instagram.css/)
🌐 [CSS Triangle Generator](http://triangle.designyourcode.io/)
🌐 [Loading.io - custom loading animations](https://loading.io/spinner/)
💻 [Epic Spinners - loading animations](http://epic-spinners.epicmax.co/)
💻  [Static CSS Gradient generator](http://angrytools.com/css-generator/gradient/)
💻  [Animista.net - custom CSS animations generator](http://animista.net/)
💻  [CSS Prefixer](http://pleeease.io/play/)

## CSS Frameworks

🌐 [Purecss.io - CSS with a minimal footprint.](https://purecss.io/)
🌐 [Spectre.css - a Lightweight, Responsive and Modern CSS Framework](https://picturepan2.github.io/spectre/)
🌐 [Bootstrap 4 Builder](https://bootstrap.build/app/v4.0/)
🌐 [Skeleton.css - Responsive CSS Boilerplate](http://getskeleton.com/)
🌐 [Bulma.io - a modern CSS framework](https://bulma.io/)
🌐 [Material Design Lite](https://getmdl.io/index.html)
🌐 [Materialize](http://materializecss.com/)
🌐 [UIkit](https://getuikit.com/)
🌐 [Semantic UI](https://semantic-ui.com/)
🌐 [Base](http://getbase.org/)
🌐 [WebUI mobile-first CSS](https://asyncdesign.github.io/webui/index.html)
🌐 [TACHYONS - CSS Toolkip](http://tachyons.io/)
🌐 [RocketCSS](http://rocketcss.org/)
🌐 [Cutestrap](https://www.cutestrap.com/)
🌐 [Blaze](https://www.blazeui.com/)
🌐 [KarmaCSS](https://karmacss.com/)
🌐 [BassCSS](http://basscss.com/)

## SCSS
🌐 [Sierra](https://sierra-library.github.io/)

## CSS & JS
🌐 [Kube - CSS & JS Framework](https://imperavi.com/kube/)
🌐 [Micron.js](https://webkul.github.io/micron/)

## JS
🌐 [sorttable - VanillaJS table-sorting plugin](https://kryogenix.org/code/browser/sorttable/)
🌐 [SweetAlert2 - a beautiful, responsive, highly customizable and accessible (WAI-ARIA) replacement for JavaScript's popup boxes. ](https://sweetalert2.github.io/)
🌐 [TippyJS - a lightweight, vanilla JS tooltip library](https://github.com/atomiks/tippyjs)

## JSON
🔗 [JSON Country List](http://www.phpied.com/files/countries/list.json)

## UX/Design
💻  [GoodWeb.design - design inspiration](http://www.goodweb.design/)

## Applications
🌐 [Atom - A hackable text editor](https://atom.io/)
🌐 [SublimeText](https://www.sublimetext.com/)

## unsure about category
💻 [SVG Cleaner](https://jakearchibald.github.io/svgomg/)
💻 [Compress Images - JPG, PNG, PDF](http://compresspng.com/)
💻 [HTML minifier](https://kangax.github.io/html-minifier/)
💻 [JSCompress - JS minifier](https://jscompress.com/)
💻 [CSSMinifier](https://cssminifier.com/)

## Icons
🌐 [Plenty of Icon cheat-sheets](https://aalmiray.github.io/ikonli/)
🌐 [SimpleSVG - sanitized and curated list of all free SVG icon packs](https://simplesvg.com/icon-sets/)
🌐 [Octicons - Github](https://octicons.github.com/)

**Comment by kieranmv95** [comment]
Legend these are great. I will update them and add them in as soon as i can!
