### ISSUE TITLE
Bootstrap 4 stuff

### ISSUE THREAD

**Issue by arechsteiner** [kieranmv95/Front-End-Wizard#40]
Maybe you'd consider adding some of these Bootstrap resources I made:

Interactive cheat sheet of Bootstrap 4 classes (with code samples):
https://hackerthemes.com/bootstrap-cheatsheet/

Bunch of open source Bootstrap themes:
https://hackerthemes.com/

Bootstrap 4 theme kit with a guide and video on how to create your own Bootstrap themes:
https://hackerthemes.com/kit/

Cheers!

**Comment by kieranmv95** [comment]
Adding the backlog of links in today and tomorrow then i will get them in!
